pkg/kubelet/prober/prober.go

Cherry-pick of 
* https://github.com/kubernetes/kubernetes/pull/84792
* https://github.com/kubernetes/kubernetes/pull/85225
Fixes the `No ref for container` issue and removes the `RefManager` struct.
https://datadoghq.atlassian.net/browse/COMPUTE-187

`No ref` fix for DD internal use - merge to 1.10-dd

---

pkg/proxy/ipvs/netlink.go
pkg/proxy/ipvs/netlink_linux.go
pkg/proxy/ipvs/netlink_unsupported.go
pkg/proxy/ipvs/proxier.go
pkg/proxy/ipvs/testing/fake.go
pkg/proxy/ipvs/testing/fake_test.go

Includes https://github.com/kubernetes/kubernetes/pull/66491 (add device to GetLocalAddresses)
Optimize syncService to avoid calling EnsureBindAddress for each service by getting all IPs bound to kube-ipvs0 and checking if the IP is in the set before calling EnsureBindAddress

Optimize binds

---

pkg/proxy/ipvs/proxier.go

Cherry-pick of https://github.com/kubernetes/kubernetes/pull/66149
This should improve performances by ~5-10% (which is good given how simple the patch is) on clusters with ~2000 services.
Flamegraphs currently show SyncIPSetEntries taking 10% of the time in this scenario and I suspect a very large part of it is related to syncing `KUBE-LOOP-BACK` which contains the list of all the endpoints in the cluster... On a large cluster this set can be huge and represent more than half of the ipset entries. In addition, the netlink library does not support ipset and kube-proxy falls back to exec + regex parsing, which is heavy for `KUBE-LOOP-BACK` (set of type `ip,port,ip`)
cc @lallydd

Only add local endpoints into the hairpin ipset

---

staging/src/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
staging/src/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming_test.go

From https://github.com/kubernetes/kubernetes/pull/72053
To avoid
```
Unable to decode an event from the watch stream: object to decode was longer than maximum allowed size
```
e.g. [this](https://ddstaging.datadoghq.com/logs?agg_q=kubernetes_cluster&cols=&event=AQAAAXDUCdP9za_dZwAAAABBWERVQ2Q0eWg3cEFwVHhLeElBSQ&from_ts=1584011494550&index=k8s-platform&live=true&messageDisplay=inline&panel=%22%22&query=%22Unable+to+decode+an+event+from+the+watch+stream%3A+object+to+decode+was+longer+than+maximum+allowed+size%22&stream_sort=desc&to_ts=1584097894550&top_n=10)

Increase limit for object size in streaming serializer

---

pkg/kubelet/kubelet_pods.go

**What this PR does / why we need it**:
There is a race condition between the kubelet `SyncLoop` when the PLEG issues a `ContainerDied` event and the pod worker `syncPod` call.
This race condition is triggered by : 
- In the SyncLoop, the call to `cleanUpContainersInPod` which in turn calls `generateAPIPodStatus` on a podStatus pointer fetched from the pod cache https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2211-L2222
- In the pod workers, the call to `syncPod` which in turn also calls `generateAPIPodStatus` on a podStatus pointer fetched from the pod cache https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1494
`generateAPIPodStatus` would eventually call `convertToAPIContainerStatuses` that sorts podStatus.ContainerStatuses in …

Fix race condition in calls to convertToAPIContainerStatuses

---

pkg/cloudprovider/providers/aws/aws.go
pkg/cloudprovider/providers/aws/aws_fakes.go
pkg/cloudprovider/providers/aws/aws_test.go
pkg/cloudprovider/providers/aws/instances.go
pkg/cloudprovider/providers/aws/instances_test.go
pkg/cloudprovider/providers/aws/volumes.go

* Lookup by instance-id in aws.go getInstancesByNodeNames()
* Use node-informer for getCandidateZonesForDynamicVolume() (eliminates describe-instances call to retrieve all running instances)
* Make DescribeInstances() log the AWS requestID on error

AWS optimisations for getInstancesByNodeNames() and getCandidateZonesForDynamicVolume()

---

pkg/proxy/ipvs/proxier.go
pkg/util/ipvs/BUILD
pkg/util/ipvs/ipvs.go
pkg/util/ipvs/kernelcheck_linux.go
pkg/util/ipvs/kernelcheck_linux_test.go
staging/src/k8s.io/apimachinery/pkg/util/version/BUILD
staging/src/k8s.io/apimachinery/pkg/util/version/doc.go
staging/src/k8s.io/apimachinery/pkg/util/version/version.go
staging/src/k8s.io/apimachinery/pkg/util/version/version_test.go

Cherry-pick of https://github.com/kubernetes/kubernetes/pull/70398

use 'nf_conntrack' instead of 'nf_conntrack_ipv4' for linux kernel >= 4.19

---

pkg/controller/statefulset/stateful_set_utils.go
pkg/controller/statefulset/stateful_set_utils_test.go

Cherry-picks #78853.
Updates may result in corrupted STS when volumes/env-vars are changed and a `partition` is in effect (this causes multiple STS versions to be maintained, and strategic merge patch to be applied if a pod in the partition is replaced).

Cherry-pick STS strategic merge patch fix

---

pkg/controller/daemon/BUILD
pkg/controller/daemon/daemon_controller.go
pkg/controller/daemon/daemon_controller_test.go

Fixes [COMPUTE-444](https://datadoghq.atlassian.net/browse/COMPUTE-444)
Cherry pick of [65009](https://github.com/kubernetes/kubernetes/pull/65009) and [64916](https://github.com/kubernetes/kubernetes/pull/64916)
Applied the patches on `release-1.10-dd` and profiled the performance of CM on a test kubemark cluster with 4k nodes.
We see significant improvement in `kube_controller_manager.queue.latency.quantile`
[64916](https://github.com/kubernetes/kubernetes/pull/64916) avoids deep copy in `metav1.IsControlledBy` and  [65009](https://github.com/kubernetes/kubernetes/pull/65009) builds an index on top of already existing cache.

Fix for degraded perf. of controller manager [daemonset] on vintage clusters

---

pkg/controller/statefulset/stateful_pod_control.go
pkg/controller/statefulset/stateful_pod_control_test.go

Cherry-picks [kubernetes PR# 93457 :: Do not create StatefulSet pods when PVC is being deleted](https://github.com/kubernetes/kubernetes/pull/93457) into 1.14.dd branch
I found PR#93457 to be mis-leading. The code review from cofyc requests 'add PVC reconciliation'. In response, a _suggested_ change was then posted as a comment, but never actually committed on the branch. So now it stands to reason that the issue brought up by member cofyc may still be an issue based on the remark:
> yes, after some investigations, we found that hitting the issue (pod has no PVC to use) is high if the PVC is deleted after the controller checks the PVC's state because the PVC can be deleted successfully if the newly created pod is not scheduled, see the discussion here: #74374
my suggestions:
o checking …

[1.14-dd] BackPort of kubernetes PR# 93457

---

.github/workflows/dd-build.yml

Add github action configuration 
To create releases on tags having `-dd` in the name 
We build `arm` and `linux`
In the future we could add another action to launch e2e test

[ci] - Add github action

---

pkg/kubelet/kubelet_pods.go

See #19 .
Ports the fix to kube 1.14.

K1.14: Fix race condition in calls to convertToAPIContainerStatuses

---

pkg/kubelet/kubelet_pods.go

Ports #19 to Kube 1.19.
Cherry-picked from https://github.com/kubernetes/kubernetes/pull/90216/commits/3d49941a43c0c1352794c4eb7b8a880de1309283

K1.19: Fix race condition in calls to convertToAPIContainerStatuses

---

cmd/kube-proxy/app/server.go

`--resource-container=""` does not seem to work, so instead we ensure
the resource container is never created.

Ensure resource-container is never created for kube-proxy / COMPUTE-1102

---

staging/src/k8s.io/apimachinery/pkg/labels/selector.go

Backport fix 66480 that is fixing a concurrency issue while working with `nodeSelectorTerms`
https://github.com/kubernetes/kubernetes/pull/66480
This bug is impacting the node-replacement feature (and potentially other scheduling) because it is using nodeSelectorTerms with multiple values.
The backport could be validated on `fury`.

backport patch #66480 to fix scheduling issue in 1.10

---

.github/workflows/dd-build.yml
pkg/cloudprovider/providers/aws/aws.go
pkg/cloudprovider/providers/aws/aws_fakes.go
pkg/cloudprovider/providers/aws/instances.go

/kind bug
For large clusters and AWS projects, the describeInstances api call returns a 500 http error because the response exceed the limit in the AWS api.
This means that, for example, for a classic loadbalancer, no new nodes get added to it, which could lead to service disruption over time due to node attrition.
This PR attempts to solve that by changing the call to use the pagination method from the aws sdk, and iterating over the instances in the paginated responses.
```release-note
NONE
```
```docs
```

Add pagination to describeInstances in aws

---

vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go

Backports equivalent of runc commit
https://github.com/opencontainers/runc/pull/2117/commits/518c855833c4920f9901f47f2a520425a33cceb4
and a few extra tidbits that must have come with some preceding commits.
Strips all code/checks around systemd's allowance of delegation on slice/scope units.

COMPUTE-1555 / Bumps runc to remove systemd unit delegation check

---

.github/workflows/dd-build.yml

`fetch-depth: 0` says "pull the whole history". We should use the default instead.
Also, upgrade to v3 while we're at it.

[ghactions] Upgrade to checkout v3 + don't pull history

---

staging/src/k8s.io/legacy-cloud-providers/aws/aws.go

Cherry pick https://github.com/kubernetes/cloud-provider-aws/pull/484 To mainline to benefits from the patch.

Handle wrapped error for InvalidInstanceID.NotFound in InstanceExists ByProviderID

---

pkg/kubelet/kubelet.go
pkg/kubelet/kuberuntime/kuberuntime_container.go
pkg/kubelet/kuberuntime/kuberuntime_manager.go
pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
pkg/kubelet/kuberuntime/kuberuntime_termination_order.go
pkg/kubelet/kuberuntime/labels.go
pkg/kubelet/status/status_manager.go
test/e2e/node/pods.go

Datadog: **NOT FROM UPSTREAM K8S**. From Lyft: https://github.com/lyft/kubernetes/commit/266a18a5839fa7a5b588063749c60c2c326b1dd8
This commit is the combination of multiple commits we've done to cherry pick and bring lyft sidecars across the ages.
datadog:patch
```?   	k8s.io/kubernetes/pkg/kubelet/apis/config/fuzzer	[no test files]
ok  	k8s.io/kubernetes/pkg/kubelet	(cached)
?   	k8s.io/kubernetes/pkg/kubelet/apis/config/v1	[no test files]
?   	k8s.io/kubernetes/pkg/kubelet/apis/config/v1alpha1	[no test files]
?   	k8s.io/kubernetes/pkg/kubelet/apis/grpc	[no test files]
ok  	k8s.io/kubernetes/pkg/kubelet/apis/config	(cached)
?   	k8s.io/kubernetes/pkg/kubelet/apis/podresources/testing	[no test files]
ok  	k8s.io/kubernetes/pkg/kubelet/apis/config/scheme	(cached)
? …
```

Sidecar: Enable Lyft type sidecars

---

.github/workflows/dd-build.yml
build/build-image/Dockerfile
cmd/kube-apiserver/fips.go
cmd/kube-controller-manager/fips.go
cmd/kube-scheduler/fips.go
cmd/kubectl/fips.go
cmd/kubelet/fips.go
pkg/kubelet/kubelet.go
pkg/kubelet/kuberuntime/kuberuntime_container.go
pkg/kubelet/kuberuntime/kuberuntime_manager.go
pkg/kubelet/kuberuntime/kuberuntime_manager_test.go
pkg/kubelet/kuberuntime/kuberuntime_termination_order.go
pkg/kubelet/kuberuntime/labels.go
pkg/kubelet/status/status_manager.go
pkg/scheduler/framework/plugins/volumebinding/binder.go
pkg/scheduler/framework/plugins/volumebinding/volume_binding.go
pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go
staging/src/k8s.io/apiserver/pkg/storage/cacher/cache_watcher.go
staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go
staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go
staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache_interval.go
staging/src/k8s.io/apiserver/pkg/storage/testing/utils.go
staging/src/k8s.io/apiserver/pkg/storage/testing/watcher_tests.go
staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
staging/src/k8s.io/apiserver/pkg/util/flowcontrol/exempt_borrowing_test.go
test/e2e/node/pods.go
test/integration/volumescheduling/volume_binding_test.go

- Similarly to https://github.com/DataDog/kubernetes/pull/91, squashed all github action changes in one commit https://github.com/DataDog/kubernetes/commit/2d86a096993fa76c8d48730d105d164393ec3af2
- Need to keep https://github.com/DataDog/kubernetes/commit/eb6ec31c05a3510b870c3a1deee0cd913ebd170a as https://github.com/kubernetes/kubernetes/pull/125398/commits/4ef58b287747f03ad8f6270bb7cabba1283836d9 only appears in 1.32
- Kept https://github.com/DataDog/kubernetes/commit/54cedb9303e55750d7832935f701b573b140ab80 as we maintain it in 1.31, see https://github.com/DataDog/kubernetes/pull/85
- Need to keep https://github.com/DataDog/kubernetes/commit/e3561514397866e174ea0b82b1086e1a254886ae as https://github.com/kubernetes/kubernetes/pull/127012/commits/723920253349ee3c272c5b5a77e9d19548c1533c …

Release v1.31.6-dd.1

---

pkg/controller/daemon/daemon_controller.go
pkg/controller/daemon/daemon_controller_test.go

Backport https://github.com/kubernetes/kubernetes/pull/129315
Same as https://github.com/DataDog/kubernetes/pull/95 but on kubernetes 1.32

[fix] fix ds controller deletes pod when not match RequiredDuringSchedulingIgnoredDuringExecution

---

staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go

/kind bug
When updating the resource quota, `e.checkAttributes` calls `e.checkQuotas` up to 3 times. This is to prevent transient failures when updating the resource quota object via `e.quotaAccessor.UpdateQuotaStatus`. In case of an error, we call  `e.checkQuotas` again and we decrement the remaining retries.
On busy clusters, we might exhaust the 3 retries before making a successful update, bubbling up the error to the client.
This PR is adding a check to avoid decrementing the retries when the error is because of a conflict. While this might increase the processing times because of the additional retries, there are two benefits:
- doesn't bubble up the error to the user
- we're still respecting the 10s timeout
If upstream doesn't like this approach, we might consider switching to a …

Conflicts on update don't count as retry
